language: csharp
sudo: required
mono: none
dist: xenial
  
branches:
  except:
    - 1.0
    - 2.0
    - 2.1
    - dse_3.1

matrix:
  include:
    - dotnet: 3.1.300
      env: TARGETF="netcoreapp3.1" BuildCoreOnly=True NETCORE_RUNTIME="3.1"
    - dotnet: 2.2.204
      env: TARGETF="netcoreapp2.1" NETCORE_RUNTIME=2.1 BuildCoreOnly=True
    - dotnet: 2.1.202
      env: TARGETF="netcoreapp2.0" NETCORE_RUNTIME=2.0 BuildCoreOnly=True

before_install:
  - sudo apt-get -y install dotnet-sdk-3.1

script:
  - dotnet --info
  - dotnet restore src
  - dotnet build src/Dse.Test.Unit/Dse.Test.Unit.csproj --no-restore -c Release
  - dotnet test src/Dse.Test.Unit/Dse.Test.Unit.csproj --no-restore --no-build -v n -c Release -f $TARGETF