schedules:
  commit:
    # Run short suite on commit
    schedule: per_commit
    matrix:
      exclude:      
        # Only build with latest for mono and netstandard 2.0
        - dotnet: ['mono', 'netcoreapp2.1']
          cassandra: ['dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0']
        # Only build with latest minor for each all majors for netstandard 1.5
        - dotnet: 'netcoreapp2.0'
          cassandra: ['dse-5.0', 'dse-6.0']
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, dse, master, etc).
      include: ["/((\\d+(\\.[\\dx]+)+)|dse|master)/"]
  adhoc:
    # Adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
    schedule: adhoc
    branches:
      exclude: ["/((\\d+(\\.[\\dx]+)+)|dse|master)/"]
os:
  - ubuntu/bionic64/csharp-driver
cassandra:
  - dse-4.8
  - dse-5.0
  - dse-5.1
  - dse-6.0
  - dse-6.7
dotnet:
  - 'mono'
  - 'netcoreapp2.0'
  - 'netcoreapp2.1'
build:
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      export SIMULACRON_PATH=$HOME/simulacron.jar
      export CCM_PATH=$HOME/ccm
      export DSE_INITIAL_IPPREFIX="127.0.0."
      export DSE_BRANCH=$CCM_BRANCH
      export DSE_VERSION=$CCM_VERSION
      export DSE_IN_REMOTE_SERVER="false"

      if [ $DSE_VERSION = '6.0' ]; then
          echo "Setting DSE 6.0 install-dir"
          export DSE_PATH=$CCM_INSTALL_DIR
      fi
      
      echo $DSE_VERSION
      echo $DSE_PATH
      echo $DSE_INITIAL_IPPREFIX
      echo $CSHARP_VERSION

      # Define Cassandra runtime
      echo "========== Setting Server Version =========="
      export CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION

      echo "========== Copying ssl files to $HOME/ssl =========="
      cp -r /home/jenkins/ccm/ssl $HOME/ssl
      
      export SNI_ENABLED="true"
      export SINGLE_ENDPOINT_PATH="${HOME}/proxy/run.sh"
      export SNI_CERTIFICATE_PATH="${HOME}/proxy/certs/client_key.pfx"
      export SNI_CA_PATH="${HOME}/proxy/certs/root.crt"
      
      echo $SNI_ENABLED
      echo $SINGLE_ENDPOINT_PATH
      echo $SNI_CERTIFICATE_PATH
      echo $SNI_CA_PATH
      
      ls "${HOME}/proxy/"
 
      if [ $DOTNET_VERSION = 'mono' ]; then      
          echo "========== Starting Mono Build =========="
          mono --version
          # Define alias for Nuget
          nuget() {
                mono /usr/local/bin/nuget.exe "$@"
          }
          export -f nuget

          # Install the required packages
          export EnableNuGetPackageRestore=true
          msbuild /t:restore /v:m src/Dse.sln
          nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

          # Compile the driver and test code
          msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Dse.sln

          # Run the tests
          echo "==========RUNNING FULL SUITE OF TESTS=========="
          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Dse.Test.Integration/bin/Release/net452/Dse.Test.Integration.dll --where "cat != long && cat != memory" --labels=All --result:"TestResult.xml" || error=true
          
          #Fail the build if there was an error
          if [ $error ]
          then 
              exit -1
          fi
      else
          echo "========== Starting .NET Core Build =========="
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet --version

          # Install the required packages
          dotnet restore src

          # Run the tests
          echo "==========RUNNING FULL SUITE OF TESTS=========="
          dotnet test src/Dse.Test.Integration/Dse.Test.Integration.csproj -v n -f $DOTNET_VERSION -c Release --filter "(TestCategory!=long)&(TestCategory!=memory)" --logger "nunit;LogFilePath=../../TestResult.xml"  || error=true
          
          #Fail the build if there was an error
          if [ $error ]
          then 
              exit -1
          fi
      fi

  - nunit:
    - "TestResult.xml"

